=== shorodilov/publications/src/metadata.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "metadata.schema.json",
  "title": "Pandoc Metadata File Schema",
  "$comment": "https://pandoc.org/MANUAL.html",
  "type": "object",
  "properties": {
    "title": {
      "type": "string"
    },
    "pagetitle": {
      "description": "The page title in HTML; equal to title by default",
      "type": "string"
    },
    "author": {
      "description": "The document author(s)",
      "$ref": "#/$defs/type-person-or-list-person"
    },
    "date": {
      "description": "The document's publication date",
      "type": "string"
    },
    "subtitle": {
      "type": "string"
    },
    "abstract": {
      "type": "string"
    },
    "abstract-title": {
      "type": "string"
    },
    "keywords": {
      "description": "The list of keywords to be included in HTML, PDF, ODT, pptx, docx and AsciiDoc",
      "$ref": "#/$defs/type-list-str"
    },
    "subject": {
      "type": "string"
    },
    "description": {
      "description": "Document description",
      "type": "string"
    },
    "category": {
      "description": "Document category",
      "type": "string"
    },
    "lang": {
      "description": "Identifies the main language of the document using IETF language tags",
      "examples": [ "en", "en-GB", "uk", "uk-UA" ],
      "type": "string"
    },
    "dir": {
      "description": "The base script direction",
      "enum": [ "ltr", "rtl" ]
    },
    "classoption": {
      "description": "Option for document class, e.g. oneside",
      "$ref": "#/$defs/type-list-str"
    },
    "documentclass": {
      "enum": [
        "article",
        "book",
        "report",
        "scrartcl",
        "scrbook",
        "scrreprt",
        "memoir"
      ]
    },
    "geometry": {
      "description": "Option for `geometry` package",
      "examples": [
        [ "margin=1in" ],
        [ "top=30mm", "left=20mm" ],
        [ "heightrounded" ]
      ],
      "$ref": "#/$defs/type-list-str"
    },
    "hyperrefoptions": {
      "$ref": "#/$defs/type-list-str"
    },
    "indent": {
      "type": "boolean"
    },
    "linestretch": {
      "type": "number"
    },
    "margin-left": {
      "description": "Sets margin if `geometry` is not used",
      "$ref": "#/$defs/margin"
    },
    "margin-right": {
      "description": "Sets margin if `geometry` is not used",
      "$ref": "#/$defs/margin"
    },
    "margin-top": {
      "description": "Sets margin if `geometry` is not used",
      "$ref": "#/$defs/margin"
    },
    "margin-bottom": {
      "description": "Sets margin if `geometry` is not used",
      "$ref": "#/$defs/margin"
    },
    "pagestyle": {
      "enum": [ "plain", "empty", "headings" ]
    },
    "papersize": {
      "description": "Paper size",
      "examples": [ "letter", "a4" ],
      "type": "string"
    },
    "secnumdepth": {
      "description": "numbering depth for sections",
      "type": "integer"
    },
    "csquotes": {
      "type": "boolean"
    },
    "csquotesoptions": {
      "description": "Options to use with `csquotes` package",
      "$ref": "#/$defs/type-list-str"
    },
    "babeloptions": {
      "description": "Options to pass to the babel package",
      "$ref": "#/$defs/type-list-str"
    },
    "fontenc": {
      "description": "Allows font encoding to be specified through `fontenc` package",
      "examples": [ "T1", "T2A", "T2B", "T3" ],
      "type": "string"
    },
    "fontfamily": {
      "type": "string"
    },
    "fontfamilyoptions": {
      "description": "Options for package used as `fontfamily`",
      "$ref": "#/$defs/type-list-str"
    },
    "fontsize": {
      "description": "Font size for body text",
      "examples": [ "10pt", "11pt", "12pt" ],
      "type": "string"
    },
    "mainfont": {
      "$ref": "#/$defs/font"
    },
    "sansfont": {
      "$ref": "#/$defs/font"
    },
    "monofont": {
      "$ref": "#/$defs/font"
    },
    "mathfont": {
      "$ref": "#/$defs/font"
    },
    "CJKmainfont": {
      "$ref": "#/$defs/font"
    },
    "CJKsansfont": {
      "$ref": "#/$defs/font"
    },
    "CJKmonofont": {
      "$ref": "#/$defs/font"
    },
    "mainfontoptions": {
      "$ref": "#/$defs/font-options"
    },
    "sansfontoptions": {
      "$ref": "#/$defs/font-options"
    },
    "monofontoptions": {
      "$ref": "#/$defs/font-options"
    },
    "mathfontoptions": {
      "$ref": "#/$defs/font-options"
    },
    "CJKoptions": {
      "$ref": "#/$defs/font-options"
    },
    "luatexjapresetoptions": {
      "$ref": "#/$defs/font-options"
    },
    "mainfontfallback": {
      "$ref": "#/$defs/font-list"
    },
    "sansfontfallback": {
      "$ref": "#/$defs/font-list"
    },
    "monofontfallback": {
      "$ref": "#/$defs/font-list"
    },
    "babelfonts": {
      "$ref": "#/$defs/font-map"
    },
    "microtypeoptions": {
      "$ref": "#/$defs/type-list-str"
    },
    "lof": {
      "description": "List of figures",
      "type": "boolean"
    },
    "lot": {
      "description": "List of tables",
      "type": "boolean"
    },
    "thanks": {
      "type": "string"
    },
    "toc": {
      "type": "boolean"
    },
    "toc-depth": {
      "type": "integer"
    },
    "biblatexoptions": {
      "$ref": "#/$defs/type-list-str"
    },
    "biblio-style": {
      "type": "string"
    },
    "biblio-title": {
      "type": "string"
    },
    "bibliography": {
      "$ref": "#/$defs/type-str-or-list-str"
    },
    "natbiboptions": {
      "$ref": "#/$defs/type-list-str"
    }
  },
  "$defs": {
    "type-list-str": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "type-str-or-list-str": {
      "oneOf": [
        {
          "type": "string"
        },
        {
          "$ref": "#/$defs/type-list-str"
        }
      ]
    },
    "type-person-or-list-person": {
      "oneOf": [
        {
          "$ref": "#/$defs/person"
        },
        {
          "type": "array",
          "items": {
            "$ref": "#/$defs/person"
          }
        }
      ]
    },
    "person": {
      "oneOf": [
        {
          "type": "string"
        },
        {
          "$comment": "author object requires custom template",
          "type": "object",
          "required": [ "name" ],
          "properties": {
            "name": {
              "type": "string"
            },
            "affiliation": {
              "type": "string"
            }
          }
        }
      ]
    },
    "margin": {
      "type": "string"
    },
    "font": {
      "type": "string"
    },
    "font-list": {
      "$ref": "#/$defs/type-list-str"
    },
    "font-map": {
      "examples": [
        {
          "chinese-hant": "Noto Serif CJK TC",
          "ukrainian": "Noto Serif"
        }
      ],
      "type": "object",
      "additionalProperties": {
        "type": "string"
      }
    },
    "font-options": {
      "oneOf": [
        {
          "type": "string"
        },
        {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      ]
    }
  }
}

=== shorodilov/publications/src/cs50-review/metadata.json
{
  "title": "CS50 - найкращий онлайн курс для початківців від Гарварда?",
  "subtitle": "Універсальний посібник для початківців",
  "author": "Сергій Городілов",
  "date": "2025-05-13",
  "keywords": [
    "review",
    "cs50",
    "programming",
    "beginner",
    "guide"
  ],
  "subject": "CS50 - Introduction to Computer Science",
  "category": "Review",
  "bibliography": "refs.bib",
  "abstract": "Ця стаття пропонує критичний погляд без прикрас на популярний онлайн-курс\nвступу до програмування CS50 від університету Гарварда. У ній розглядаються\nзміст курсу та методика викладання, а також наводяться характеристики\nособливостей його подачі та мета навчання. Досліджується чи є обґрунтованою\nрепутація CS50 як найкращого вступного курсу для початківців, аналізуються\nпереваги та недоліки. Стаття має на меті допомогти читачам сформувати власну\nдумку щодо доцільності вивчення CS50 для старту кар'єри в IT-сфері."
}
